services:
  fastapi:
    build: ./fastapi
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/app/logs
    depends_on:
      - fastapi