input {
    file {
        path => "/app/logs/access.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        type => "access"
    }

    file {
        path => "/app/logs/error.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        type => "error"
    }
}

filter {
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "fastapi-logs-%{+YYYY.MM.dd}"
    }

    stdout {
        codec => rubydebug
    }
}